version: '3.8'

services:
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: PortfolioAPI
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "9922:3306"