server:
  port: 5555

app:
  jwt:
    secret: ${JWT_SECRET:your-256-bit-secret-base64-encoded}
    access-token-expiration: 86400000 # 24 saat
    refresh-token-expiration: 604800000 # 7 gün
    issuer: your-app-name


spring:
  datasource:
    url: jdbc:mysql://localhost:9922/PortfolioAPI
    username: user
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
